#
# Site settings
#
title: Simius Ex Machina
description: >
  Personal blog of Guillermo about
  programming languages, compilers, interpreters, virtual machines
  and software engineering in general.
email: guillermocalvo@yahoo.com
baseurl:
url:
twitter_username: guillermonkey
github_username:  guillermocalvo

#
# Build settings
#
markdown: kramdown

#
# Pagination
#
paginate: 10
paginate_path: /archive/page/:num/

#
# Default values
#
defaults:
  -
    scope:
      path: blog
      type: posts
    values:
      layout: blog
  -
    scope:
      path: quotes
      type: posts
    values:
      layout: quote
  -
    scope:
      path: quotes/page
      type: pages
    values:
      title: Programming Quotes
      layout: listing
      listing:
        include_file: listing-quotes.html
        source:
          type: posts
          category: quotes
        navigation:
          bottom: true
      paginator:
        path_first: /quotes/page/
        path: /quotes/page/:num/
        per_page: 50
