#
# Site settings
#
title: Simius Ex Machina
description: Personal blog about programming, technology and software engineering in general.
url: https://guillermocalvo.github.io
baseurl:
twitter: SimiusExMachina
locale:
  language: en
  territory: us

#
# Site owner
#
owner:
  name: Guillermo Calvo
  avatar: guillermo.png
  about:
    link: /about/
    title: About me
  bio: Seeking the troof through programming.
  email: guillermocalvo@yahoo.com
  disqus-shortname: guillermocalvo-github-io
  twitter: guillermonkey
  google:
    plus: GuillermoCalvo
    analytics: UA-61670496-2
    verify: google4b20f13f27a4818e.html
  github: guillermocalvo
  stackoverflow: 534374/guillermo
  linkedin: guillermocalvo
  tumblr: guillermonkey

#
# Build settings
#
permalink:   /:categories/:year/:month/:day/:title.html
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed
compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  ignore:
    envs: [development]
gems:
  - jekyll-sitemap

#
# Pagination
#
paginate: 20
paginate_path: /archive/page/:num/

#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      share: true
      taglist: true
      comments: true
      related: true
      history: true
      view_all:
        link: /archive/
        title: posts
  -
    scope:
      path: ""
      type: pages
    values:
      share: false
      taglist: false
      comments: false
      related: false
      history: false
  -
    scope:
      path: blog
      type: posts
    values:
      layout: post
      view_all:
        link: /blog/
        title: blog posts
  -
    scope:
      path: coding
      type: posts
    values:
      layout: post
      view_all:
        link: /coding/
        title: programming posts
  -
    scope:
      path: quotes
      type: posts
    values:
      layout: quote
      view_all:
        link: /quotes/page/
        title: programming quotes
      history: false
      badge: quote-left
      image:
        feature: ada-lovelace.jpg
        caption: Portrait of Ada Lovelace
        credit: Science & Society Picture Library
        creditlink: http://www.scienceandsociety.co.uk/results.asp?image=10312035
  -
    scope:
      path: tags
      type: pages
    values:
      title: Tags
      layout: tags
      image:
        feature: gift-tag.jpg
        credit: Dennis van Zuijlekom
        creditlink: https://www.flickr.com/photos/dvanzuijlekom/
      sitemap: false
  -
    scope:
      path: quotes/page
      type: pages
    values:
      title: Programming Quotes
      layout: listing
      image:
        feature: ada-lovelace.jpg
        caption: Portrait of Ada Lovelace
        credit: Science & Society Picture Library
        creditlink: http://www.scienceandsociety.co.uk/results.asp?image=10312035
      listing:
        include_file: listing-quotes.html
        source:
          type: posts
          category: quotes
        navigation:
          bottom: true
      paginator:
        path_first: /quotes/page/
        path: /quotes/page/:num/
        per_page: 50
      sitemap: false
