#
# Site settings
#
title: Leaky Abstractions
title_separator: •
description: Personal blog about programming, technology and software engineering in general.
url: https://leakyabstractions.com
baseurl:
twitter: LeakAbstraction
locale: en_US
repository: guillermocalvo/leakyabstractions


#
# Site author
#
author:
  name: &site_author_name Guillermo Calvo
  avatar: /assets/images/author/guillermo.jpg
  bio: Seeking the troof through programming.
  location: Tokyo, Japan
  uri:
  email: guillermo@leakyabstractions.com
  keybase:
  twitter: gcalvo
  facebook:
  google_plus:
  linkedin: guillermocalvo
  xing:
  tumblr:
  bitbucket: guillermocalvo
  github: guillermocalvo
  stackoverflow: 534374/guillermo
  lastfm:
  dribbble:
  pinterest:
  foursquare:
  steam:
  youtube:
  soundcloud:
  weibo:
  flickr:
  codepen:
  vine:
  telegram: guillermocalvo


#
# Theme settings
#
theme: minimal-mistakes-jekyll
name: *site_author_name
timezone: Europe/Madrid
teaser: /assets/images/header/teaser/chimp.jpg
breadcrumbs: false
words_per_minute: 200
atom_feed:
  path: /feed.xml

# Comment settings
comments:
  provider: disqus
  disqus:
    shortname: leakyabstractions

# SEO Related
google_site_verification: Ch9BjSSbuXSH37m32EOBw1ibbwk9VR5TuUuM4Kxf0XU
bing_site_verification: 77F6CF1F1E66E82D8F062B7A3E633F67

# Analytics
analytics:
  provider: google-universal
  google:
    tracking_id: UA-97888471-1

# Social Sharing
twitter:
  username: LeakAbstraction

# Open Graph/Twitter default site image
og_image: /assets/images/site-logo.png

# For specifying social profiles
social:
  type: Person
  name: *site_author_name
  links: # An array of links to social media profiles
    - https://twitter.com/gcalvo
    - https://twitter.com/LeakAbstraction


#
# Build settings
#
permalink:   /posts/:year/:month/:day/:title.html
incremental: false
encoding: utf-8
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
keep_files:
  - .git
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed
compress_html:
  clippings: all
  comments: []
  blanklines: false
  startings: []
  endings: []
  profile: false
  ignore:
    envs: []
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


#
# Pagination
#
paginate: 16
paginate_path: /blog/:num/


#
# Default values
#
defaults:
  # _posts
  -
    scope:
      path: ""
      type: posts
    values:
      layout: single
      category: blog
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _drafts
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: single
      category: blog
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _quotes
  -
    scope:
      path: ""
      type: quotes
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      header:
        teaser: /assets/images/header/teaser/ada-lovelace.jpg
        image: /assets/images/header/ada-lovelace.jpg
        caption: "Photo credit: Portrait of Ada Lovelace [**Science & Society Picture Library**](http://www.scienceandsociety.co.uk/results.asp?image=10312035)"


#
# Collections
#
collections:
  quotes:
    output: true
    permalink: /quotes/:title.html


#
# Archives
#
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
