#
# Site settings
#
title: Simius Ex Machina
description: Personal blog of Guillermo about programming languages, compilers, interpreters, virtual machines and software engineering in general.
baseurl:
url:
locale:
  language: en
  territory: us

#
# Site owner
#
owner:
  name: Guillermo Calvo
  avatar: guillermo.png
  bio: Seeking the troof through programming.
  email: guillermocalvo@yahoo.com
  disqus-shortname: guillermocalvo-github-io
  twitter: guillermonkey
  google:
    plus: GuillermoCalvo
    analytics: UA-61670496-2
    verify: google4b20f13f27a4818e.html
  github: guillermocalvo
  stackoverflow: 534374/guillermo
  linkedin: guillermocalvo
  tumblr: guillermonkey

#
# Build settings
#
permalink:   /:categories/:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed
compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  ignore:
    envs: [development]

#
# Pagination
#
paginate: 10
paginate_path: /archive/page/:num/

#
# Default values
#
defaults:
  -
    scope:
      path: blog
      type: posts
    values:
      layout: blog
      comments: true
  -
    scope:
      path: quotes
      type: posts
    values:
      layout: quote
      history: false
      comments: true
      image:
        feature: ada-lovelace.jpg
        caption: Portrait of Ada Lovelace
        credit: Science & Society Picture Library
        creditlink: http://www.scienceandsociety.co.uk/results.asp?image=10312035
  -
    scope:
      path: quotes/page
      type: pages
    values:
      title: Programming Quotes
      layout: listing
      image:
        feature: ada-lovelace.jpg
        caption: Portrait of Ada Lovelace
        credit: Science & Society Picture Library
        creditlink: http://www.scienceandsociety.co.uk/results.asp?image=10312035
      listing:
        include_file: listing-quotes.html
        source:
          type: posts
          category: quotes
        navigation:
          bottom: true
      paginator:
        path_first: /quotes/page/
        path: /quotes/page/:num/
        per_page: 50
